ocl bug fix and wireframe support
01org/libyami pull request #597
Opened 2016-09-20 02:39 UTC by dspmeng

ocl: fix mosaic filter out of bound issue
ocl global work size must be evenly divisible by work group size,
so global work size may be larger than the dimension of mosaicked
region.

ocl: implement wireframe
wireframe is a rectangle around the region of interest specified by
user. Also, the width and color of bordercan are both configurable.

ocl: initialize context on create
initialize ocl context on first buffer processing may take longer time
than expected, and block the pipeline. so we move ocl initialization
on create before pipeline is running.

2016-10-09 02:08 UTC, xuguangxin requested changes

2016-10-09 02:08 UTC, xuguangxin commented on vpp/Makefile.am
> +libyami_vpp_source_c += oclpostprocess_wireframe.cpp
Could we change the BUILD_OCL_BLENDER to BUILD_OCL_FILTERS

2016-10-09 02:08 UTC, xuguangxin commented on ocl/kernels/wireframe.cl
> + *  Copyright (C) 2016 Intel Corporation
we changed our license from LGPL to Apache v2.

2016-10-09 02:08 UTC, xuguangxin commented on vpp/oclpostprocess_mosaic.cpp
> +         || (CL_SUCCESS != clSetKernelArg(m_kernelMosaic, 1, sizeof(cl_mem), &bgImageMem[0]))
why other filter need ensure context in constructor, but mosaic do not need this

2016-10-09 02:08 UTC, xuguangxin commented on vpp/oclpostprocess_wireframe.h
> + *  oclpostprocess_wireframe.h - opencl based wireframe
license

2016-10-09 02:08 UTC, xuguangxin commented on vpp/oclpostprocess_wireframe.cpp
> + *  Copyright (C) 2016 Intel Corporation
license

2016-10-11 05:31 UTC, dspmeng commented
1. update license
2. add one commit to use BUILD_OCL_FILTERS in auto conf and auto make files.
commit bf28dede699cd43472be96b1e4ed6aab9b71411f
Author: Jia Meng <jia.meng@intel.com>
Date:   Tue Oct 11 13:09:25 2016 +0800

    build: replace ocl blender with ocl filters
    
    Signed-off-by: Jia Meng <jia.meng@intel.com>

2016-10-11 05:31 UTC, dspmeng commented on vpp/Makefile.am
> +libyami_vpp_source_c += oclpostprocess_wireframe.cpp
done

2016-10-11 05:31 UTC, dspmeng commented on ocl/kernels/wireframe.cl
> + *  Copyright (C) 2016 Intel Corporation
done

2016-10-11 05:31 UTC, dspmeng commented on vpp/oclpostprocess_mosaic.cpp
> +         || (CL_SUCCESS != clSetKernelArg(m_kernelMosaic, 1, sizeof(cl_mem), &bgImageMem[0]))
it is add here:
https://github.com/01org/libyami/pull/597/commits/34ce86827d22900cd7ba44d4a3d8b7fd2d56207b#diff-ddb9588b3a6e4238fbb1c3c7c667b546R39

2016-10-11 05:31 UTC, dspmeng commented on vpp/oclpostprocess_wireframe.h
> + *  oclpostprocess_wireframe.h - opencl based wireframe
done

2016-10-11 05:31 UTC, dspmeng commented on vpp/oclpostprocess_wireframe.cpp
> + *  Copyright (C) 2016 Intel Corporation
done

2016-10-13 04:54 UTC, xuguangxin approved these changes

2016-10-14 04:41 UTC, xuguangxin commented
merged as a9c3608b1e7aefc7bb2f49e76a95632676992ac6, thanks

2016-10-14 04:41 UTC, closed without merging