Flush B frame for 264 and 265, to fix #598
01org/libyami pull request #600
Opened 2016-09-22 05:05 UTC by wudping

2016-09-22 05:09 UTC, xuguangxin commented
@lizhong1008 , help to review
thanks

2016-09-22 05:15 UTC, xuguangxin commented
@lizhong1008 , please help to verify it too. thanks

2016-09-22 05:26 UTC, wudping commented
libyami-tuils, use [https://github.com/01org/libyami-utils/pull/39](url)

2016-09-22 06:35 UTC, lizhong1008 commented on encoder/vaapiencoder_h264.cpp
> +    INFO();
Why a NULL INFO here?

2016-09-22 06:37 UTC, lizhong1008 commented on encoder/vaapiencoder_hevc.cpp
> +    INFO();
a NULL INFO

2016-09-22 06:38 UTC, lizhong1008 reviewed
LGTM except some NULL INFO.

2016-09-22 06:44 UTC, lizhong1008 commented
One more thing,   please don't forget to change the commet in VideoEncoderInterface.h:
///obsolete, discard cached data (input data or encoded video frames), not sure why an encoder need this
    virtual void flush(void) = 0;

you can change it to flush cached data (input data or encoded video frames)

2016-09-22 06:52 UTC, wudping commented on encoder/vaapiencoder_h264.cpp
> +    INFO();
thanks @lizhong1008 , I will delete it.

2016-09-22 06:53 UTC, wudping commented on encoder/vaapiencoder_hevc.cpp
> +    INFO();
I will delete it.

2016-09-22 06:54 UTC, wudping commented
thanks @lizhong1008 for your constructive advise.

2016-09-22 07:29 UTC, wudping commented
updated according to advises.

2016-09-22 08:45 UTC, lizhong1008 commented
+1

2016-09-22 09:23 UTC, lizhong1008 commented
@wang-fei , please help to verify it. Don't forget to check h264 also.

2016-09-22 16:08 UTC, chivakker commented on encoder/vaapiencoder_base.cpp
>      AutoLock l(m_lock);
The line above can be removed.

2016-09-22 16:10 UTC, chivakker requested changes
This patch was merged with obvious problems especially on the encoder base class.  flush on the base class is doing nothing now.  So the proper change would be to remove all calls to base::flush in all codecs. 

Please fix it.

2016-09-23 03:19 UTC, lizhong1008 commented on encoder/vaapiencoder_base.cpp
>      AutoLock l(m_lock);
@chivakker , yes, it can be removed.  Thanks for indicate it.

2016-09-23 03:27 UTC, lizhong1008 commented on encoder/vaapiencoder_base.cpp
>      AutoLock l(m_lock);
@chivakker , "This patch was merged with obvious problems especially on the encoder base class. flush on the base class is doing nothing now. So the proper change would be to remove all calls to base::flush in all codecs. Please fix it."   Maybe we can fix h264 and h265 encoder in this patch series， and send a separated patch to fix other codecs?   We just to fix h264 and h265 b frame issue here,  what do you think?

2016-09-23 03:29 UTC, lizhong1008 commented
@xuguangxin , seems this patch has been merged without "verify +1", do we need wangfei's verification before merging it?

2016-09-23 04:23 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
>      AutoLock l(m_lock);
Hi @chivakker 
Agree with Lizhong, we should focus on h264, h265 in this patch. I think we had better not change every codec for this base on following reason:
1.	Currently, we do not have any thing in VaapiEncoderBase::flush, it do not mean we will not add something in future. 
2.	Very codec have right to choose call base class flush or not.
3.	If it is no functional or readability benefit. We had better not change the code. If we change vp9encoder, author need do test for vp9encoder. This is an extra effort for author and it's not introduce benefit 
Do you think it is make sense?

2016-09-23 07:43 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
>      AutoLock l(m_lock);
Hi @chivakker 
the flush only be call one time. remove it will not improve performance or readbility. Do we really need  remove it?

2016-09-23 07:46 UTC, xuguangxin commented
@lizhong1008 , QA is not suppose verify our pull requst  unlease it's a big update. I veirfied it.It's ok.

2016-09-23 08:22 UTC, lizhong1008 commented
@xuguangxin , so this it our alignment with QA team, right? I am ok if we get alignment.

2016-09-23 09:08 UTC, xuguangxin commented
I remember we sync with QA before, but you can double confirm it

2016-09-28 08:32 UTC, closed without merging