decoder: add flush() for h264 and h265
01org/libyami pull request #611
Opened 2016-10-08 08:04 UTC by LindaYu17

add flush() function for h264 and h265, so that we could flush dpb for
them in this function.

Signed-off-by: Linda Yu <linda.yu@intel.com>

2016-10-08 08:12 UTC, xuguangxin requested changes

2016-10-08 08:12 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_dpb.flush();
could you move all things between https://github.com/01org/libyami/blob/apache/decoder/vaapidecoder_h264.cpp#L1825 and  https://github.com/01org/libyami/blob/apache/decoder/vaapidecoder_h264.cpp#L1830 to flush? and call flush in L1825

2016-10-08 08:12 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +    m_dpb.flush();
same as h264.

2016-10-08 08:12 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +void VaapiDecoderH2665::flush(void)
this not build able

2016-10-08 08:12 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_dpb.flush();
Do we need reset parser here?

2016-10-08 08:14 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_dpb.flush();
Please check  following things need reset or not.
    YamiParser::H264::Parser m_parser;
    PicturePtr m_currPic;
    PicturePtr m_prevPic;
    bool m_newStream;
    bool m_endOfSequence;
    bool m_endOfStream;
    DPB m_dpb;
    uint32_t m_nalLengthSize;
    SurfacePtr m_currSurface;
    bool m_contextChanged;
    static const bool s_registered; // VaapiDecoderFactory registration resu

2016-10-08 08:16 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +    m_dpb.flush();
Please check following fields too
    SharedPtr<Parser> m_parser;
    PicturePtr  m_current;
    uint16_t    m_prevPicOrderCntMsb;
    int32_t     m_prevPicOrderCntLsb;
    int32_t     m_nalLengthSize;
    bool        m_associatedIrapNoRaslOutputFlag;
    bool        m_noRaslOutputFlag;
    bool        m_newStream;
    bool        m_endOfSequence;
    DPB         m_dpb;
    std::map<int32_t, uint8_t> m_pocToIndex;
    SharedPtr<SliceHeader> m_prevSlice;

2016-10-09 08:16 UTC, xuguangxin requested changes

2016-10-09 08:16 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +    m_associatedIrapNoRaslOutputFlag = false;
we do not need change this:

```
+    m_associatedIrapNoRaslOutputFlag = false;
 +    m_noRaslOutputFlag = false;
 +    m_current.reset();
 +    m_pocToIndex.clear();
```

you need change this  
`+    m_prevSlice.reset();`
to
`m_prevSlice.reset(new SliceHeader());`

2016-10-09 08:16 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +    m_associatedIrapNoRaslOutputFlag = false;
@lizhong1008 , Please help to review this pull request.
thanks

2016-10-10 02:21 UTC, lizhong1008 commented on decoder/vaapidecoder_h264.cpp
> +    m_currSurface.reset();
@xuguangxin , do we need implement the stop() interface, and move the sw/hw context resetting to stop()?

2016-10-10 02:35 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_currSurface.reset();
But flush is not stop, it do not need deinit Va. Maybe we can put all context reset thing to a standalone function like resetDecoderContext.

2016-10-10 05:06 UTC, lizhong1008 commented on decoder/vaapidecoder_h264.cpp
> +    m_currSurface.reset();
I mean we don't need reset surface in flush(), maybe we can move all surface and context into stop().

2016-10-10 09:42 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_currSurface.reset();
flush is for seek, if we do not reset m_currSurface, we will reference error surface after seek.

2016-10-13 04:53 UTC, xuguangxin commented
Hi @lizhong1008 , is it ok to start verification this?

2016-10-14 04:26 UTC, xuguangxin approved these changes

2016-10-19 08:18 UTC, xuguangxin commented
Hi @lizhong1008 , is it ok to start verification this?

2016-10-19 08:47 UTC, lizhong1008 commented
@xuguangxin LGTM

2016-10-24 02:01 UTC, xuguangxin commented
@wudping , Please help to verify this on h264 and h265 conformance.

2016-10-24 07:07 UTC, wudping commented
I am sorry, There is a problem in 264/265 decoding with this patch. Some frames are lost.
My test file is alphaconformanceG.264.
host: regression@regression,
pw: 123456
path: /home/regression/daily_regression/medias_for_verify/mediafiles/h264/alphaconformanceG.264

2016-10-24 07:08 UTC, xuguangxin commented
@wudping do not paste you password in github ;)

2016-10-24 07:10 UTC, wudping commented
okay, thanks @xuguangxin .

2016-10-24 07:12 UTC, wudping commented
I am sorry, there is a problem in decoding 265/264 with this patch. Some frames are lost.

2016-10-28 01:38 UTC, xuguangxin commented
Hi @LindaYu17 : 
Do you have time estimate for this pull request?

2016-10-28 07:26 UTC, LindaYu17 commented
will make time early next week on this!

2016-10-31 07:56 UTC, LindaYu17 commented
hi @xuguangxin I have updated this pull request.
hi @wudping could you please help to verify again?

2016-10-31 07:58 UTC, wudping commented
okay, @LindaYu17 .

2016-11-01 04:16 UTC, wudping commented
verify + 1

2016-11-09 04:46 UTC, xuguangxin commented
merged as 9eba4cfb4f9c3eb7757c421c5c37a723d37a0625. thanks Linda

2016-11-09 04:46 UTC, closed without merging