makefile: add top_srcdir into CPPFLAGS
01org/libyami pull request #612
Opened 2016-10-08 11:40 UTC by wudping

to integrate libyami into yocto, we should add top_srcdir into cppflags
to make it compiled well.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-10-08 16:15 UTC, chivakker commented
Same as review here: https://github.com/01org/libyami-utils/pull/46

2016-10-09 00:53 UTC, wudping commented
thanks @chivakker

2016-10-09 01:58 UTC, xuguangxin requested changes
All changed file have been changed to wrong mode

2016-10-09 02:06 UTC, wudping commented
thanks @xuguangxin , I will modify them.

2016-10-10 03:02 UTC, xuguangxin approved these changes

2016-10-10 15:37 UTC, chivakker commented
lgtm :+1:

2016-10-11 07:30 UTC, xuguangxin commented
merged as fb830129c9398caa2144ad8579b86b83ab80cdfc

2016-10-11 07:30 UTC, closed without merging