scale_vpp: check out odd resolution for VPP
01org/libyami pull request #616
Opened 2016-10-11 07:19 UTC by wudping

check out odd resolution for scaler VPP, if so print error, then return.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-10-11 07:21 UTC, xuguangxin requested changes

2016-10-11 07:21 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    if(dest->crop.width & 0x01 || dest->crop.height & 0x01 ||
Do not check dest->crop.width and dest->crop.height. When you do composite,it's very likely have odd resolution in dest,

2016-10-11 07:30 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +    if(dest->crop.width & 0x01 || dest->crop.height & 0x01 ||
thanks @xuguangxin , you mean that I need only to check the source crop.
YAMI can support output odd resolution, is right?

2016-10-11 08:36 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    if(dest->crop.width & 0x01 || dest->crop.height & 0x01 ||
yes,driver can support this

2016-10-11 08:39 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +    if(dest->crop.width & 0x01 || dest->crop.height & 0x01 ||
thanks @xuguangxin , I have updated it.

2016-10-12 05:19 UTC, xuguangxin approved these changes

2016-10-12 05:23 UTC, xuguangxin commented
merged as 08e2403eec7212bfff8b8928d7702ef1935d5bcc

2016-10-12 05:23 UTC, closed without merging