HEVC ENC:10bit support merged
01org/libyami pull request #645
Opened 2016-11-01 07:47 UTC by QuPengfei

add the P010 input
add support for HEVC 10bit encoding
add pixelwidthinbyte to help caculate the width of image when 8/10 bit

Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>

2016-11-01 08:58 UTC, xuguangxin commented
Hi @QuPengfei 
thanks for your patch, could your add patch on top of this pull request.https://github.com/01org/libyami/pull/638
thanks

2016-11-09 05:08 UTC, xuguangxin commented
Hi @QuPengfei 
the hevc decoder have been merged, is any update on this?
thanks

2016-11-09 18:48 UTC, chivakker requested changes
Please resolve the conflict for merging, otherwise lgtm

2016-11-22 01:52 UTC, xuguangxin commented
pengfei is busy with other things. dongping will help to rebase the code at #668 . Close this

2016-11-22 01:52 UTC, closed without merging