yami_vpp: colorbalance setting
01org/libyami pull request #651
Opened 2016-11-09 08:14 UTC by wudping

implement colorbalance setting for hue, saturation, brightness and contrast.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-11-09 08:20 UTC, wudping commented
corresponding libyami-utils as following:
https://github.com/01org/libyami-utils/pull/57

2016-11-09 18:54 UTC, chivakker reviewed
This change looks good to me other that the unnecessary change.

2016-11-09 18:54 UTC, chivakker commented on vpp/vaapipostprocess_scaler.cpp
> +
unnecessary change.

2016-11-10 01:06 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +
thanks @chivakker , I will delete line 150.

2016-11-11 01:56 UTC, xuguangxin requested changes

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    mapToRange(value, range.min_value, range.max_value, colorbalance.level, COLORBALANCE_LEVEL_MIN, COLORBALANCE_LEVEL_MAX);
please check mapToRange return value

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    d->attrib = mapToVaColorBalanceMode(colorbalance.mode);
Please check the return value

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    switch (mode) {
so many switch cases, every error prone, could you help to change to Array loop style?
Just like https://github.com/01org/libyami/blob/ef7953bc7196c959051a368b5f2c0a71ad4a0a37/v4l2/v4l2_codecbase.cpp#L620
and  https://github.com/01org/libyami/blob/ef7953bc7196c959051a368b5f2c0a71ad4a0a37/v4l2/v4l2_codecbase.cpp#L633

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +            modeRange.mode = mapToVppColorBalanceMode(caps[i].type);
Please check and drop unsupported mode.

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +        m_brightness.filter.reset();
this wired, you treat COLORBALANCE_NONE as brightness? what about other filters?

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +        m_brightness.filter.reset();
you treat none as brightness again

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.h
> +        //std::set<ColorBalanceModeRange, ColorBalanceModeRangeCompare> supportedModeRanges;
remove this

2016-11-11 01:56 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.h
> +        VppColorBalanceMode mode; //set by user
why we need mode here and  L52

2016-11-11 03:56 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +        m_brightness.filter.reset();
thanks @xuguangxin for your constructive suggestion.
How about to reset all the colorbalance filters, such as hue, contrast, brightness and saturation,  when getting COLORBALANCE_NONE ?

2016-11-11 03:56 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +        m_brightness.filter.reset();
thanks @xuguangxin .

2016-11-11 03:56 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +        m_brightness.filter.reset();
thanks @xuguangxin .

2016-11-11 03:57 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +    switch (mode) {
thanks @xuguangxin for advises.

2016-11-11 03:57 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +    mapToRange(value, range.min_value, range.max_value, colorbalance.level, COLORBALANCE_LEVEL_MIN, COLORBALANCE_LEVEL_MAX);
thanks for suggestion @xuguangxin .

2016-11-11 03:58 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +    d->attrib = mapToVaColorBalanceMode(colorbalance.mode);
thanks for suggestion @xuguangxin .

2016-11-11 04:01 UTC, wudping commented on vpp/vaapipostprocess_scaler.cpp
> +            modeRange.mode = mapToVppColorBalanceMode(caps[i].type);
thanks @xuguangxin .

2016-11-11 04:07 UTC, wudping commented on vpp/vaapipostprocess_scaler.h
> +        VppColorBalanceMode mode; //set by user
I just put VppColorBalanceMode and VAProcFilterValueRange together, so I can find out the range value via VppColorBalanceMode. 
But I will save them in a Map, according to your suggestion.
Thanks @xuguangxin .

2016-11-11 04:07 UTC, wudping commented on vpp/vaapipostprocess_scaler.h
> +        //std::set<ColorBalanceModeRange, ColorBalanceModeRangeCompare> supportedModeRanges;
okay ,thanks.

2016-11-14 09:39 UTC, wudping commented
updated according to the detail comments;
please help to review.

2016-11-18 02:52 UTC, xuguangxin approved these changes

2016-11-18 02:52 UTC, xuguangxin commented on vpp/vaapipostprocess_scaler.cpp
> +    static bool rangeInit = false;
Please do not use static, we may support difference va at same time, ie card0 or card1.

2016-11-22 04:38 UTC, xuguangxin commented
verify +1

2016-11-22 05:22 UTC, xuguangxin commented
merged as 30c7aa00b3a27b4c8802f7a755c599ccf5677a11

2016-11-22 05:22 UTC, closed without merging