vaapic: memset misc object
01org/libyami pull request #655
Opened 2016-11-10 08:33 UTC by lizhong1008

Signed-off-by: Zhong Li <zhong.li@intel.com>

2016-11-10 18:06 UTC, chivakker requested changes
The change makes sense but the commit message is rather vague.  There's no such a thing as vaapic, vaapi-encpicture has to be cleared to 0 when creating a miscellaneous object.

2016-11-11 01:56 UTC, xuguangxin commented on encoder/vaapiencpicture.h
> +        if (bufPtr)
This if is not needed, data is an array in misc, if we can access misc->type, misc->data never be NULL.

2016-11-16 02:33 UTC, lizhong1008 commented on encoder/vaapiencpicture.h
> +        if (bufPtr)
@xuguangxin misc is an input of createBufferObject,  and drive will init misc->data, may change it to NULL.  So we should check bufPtr

2016-11-16 02:44 UTC, xuguangxin commented on encoder/vaapiencpicture.h
> +        if (bufPtr)
The data's prototype is array.  misc->data will get the array address. if misc is not null, misc->data always be a valid value.

2016-11-16 03:21 UTC, lizhong1008 commented
@chivakker  yeah, your comments make sense, it is a typo. I'll update it.

2016-11-16 17:52 UTC, chivakker approved these changes

2016-11-17 04:15 UTC, wudping commented
verify + 1

2016-11-18 01:53 UTC, xuguangxin commented
merged as 0ee515f10124740a8f0d9830210be5d8d2142387

2016-11-18 01:53 UTC, closed without merging