common: Add pooled video frame allocator
01org/libyami pull request #656
Opened 2016-11-16 05:34 UTC by LindaYu17

Signed-off-by: Linda Yu <linda.yu@intel.com>

2016-11-16 05:40 UTC, xuguangxin requested changes

2016-11-16 05:40 UTC, xuguangxin commented on common/videopool.h
> +    VideoPool(std::deque<SharedPtr<T> >& buffers)
Please split this to other commit

2016-11-16 05:40 UTC, xuguangxin commented on common/Makefile.am
> +	pooledframeallocator.cpp \
Please use PooledFrameAllocator.cpp. We should follow webkit style https://webkit.org/code-style-guidelines/ for new file

2016-11-16 05:40 UTC, xuguangxin commented on common/pooledframeallocator.h
> +#define POOLED_FRAME_ALLOCATOR_H_
use PooledFrameAllocator_h, it's webkit style

2016-11-16 06:41 UTC, LindaYu17 commented
change done @xuguangxin

2016-11-16 08:55 UTC, xuguangxin approved these changes

2016-11-16 08:57 UTC, xuguangxin commented on common/PooledFrameAllocator.cpp
> +#include <PooledFrameAllocator.h>
Sorry I missed this, This should be "" instead of <>

2016-11-16 09:40 UTC, LindaYu17 commented
done @xuguangxin

2016-11-16 18:01 UTC, chivakker approved these changes
I only have one comment but it minor at this point.  If submitter sees more benefit on pushing the memset to the constructor please do.

2016-11-16 18:01 UTC, chivakker commented on common/PooledFrameAllocator.cpp
> +        memset(f.get(), 0, sizeof(VideoFrame));
This memset can be moved to the constructor of VideoFrame.  There's a similar problem with the MiscBuffer that is fixed in that way.

2016-11-17 01:22 UTC, xuguangxin commented on common/PooledFrameAllocator.cpp
> +        memset(f.get(), 0, sizeof(VideoFrame));
VideoFrame do not have constructor. It is a pod type; it will be use in capi too.

2016-11-17 01:32 UTC, xuguangxin commented on common/PooledFrameAllocator.cpp
> +        memset(f.get(), 0, sizeof(VideoFrame));
Could give more detail description for MiscBuffer thing?

2016-11-29 04:04 UTC, xuguangxin commented
merged as 9c7bb50639233a505599a17d74caa4a0dd0ee0ad

2016-11-29 04:04 UTC, closed without merging