vpp_unittest: use mocro ASSERT_TRUE() to check caps  to fix #572
01org/libyami pull request #664
Opened 2016-11-18 07:58 UTC by wudping

in function checkFilterCaps(), replace EXPECT_TRUE() with ASSERT_TRUE() to
force this function return when pointer 'caps' is NULL.
If use EXPECT_TRUE(bool(caps)), the function will continue when caps is NULL,
then it will access NULL pointer, rase up segmentation fault.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-11-18 07:58 UTC, wudping commented
please help to review.

2016-11-18 17:47 UTC, uartie requested changes
Please add "Fixes #572" to the commit message body for proper github linking and tracking.  This will also ensure it's part of git history.

The rest of the change looks good.

2016-11-22 05:32 UTC, wudping commented
okay, thanks @uartie

2016-11-22 16:05 UTC, uartie approved these changes

2016-11-22 18:43 UTC, chivakker approved these changes

2016-11-23 05:18 UTC, xuguangxin commented
merged as 3376fbf82bbcb6fdd1438888e0a3fcf390241576

2016-11-23 05:18 UTC, closed without merging