HEVC ENC:10bit support merged
01org/libyami pull request #668
Opened 2016-11-22 01:23 UTC by wudping

add the P010 input
add support for HEVC 10bit encoding
add pixelwidthinbyte to help caculate the width of image when 8/10 bit

Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>
Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-11-22 01:25 UTC, wudping commented
hevc encode 10-bits, rebase Pengfei's patch. please help to review.

2016-11-22 01:42 UTC, xuguangxin requested changes

2016-11-22 01:42 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
> +        rtFormat = VA_RT_FORMAT_YUV420_10BPP;
this will build failed on libva 0.37. Could you use getRtFormat and check the return value?

2016-11-22 01:42 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
> +    if (m_videoParamCommon.bitDepth == 10)
could you return error for other bitDepth, like 12, 15 etc.

2016-11-23 06:53 UTC, wudping commented on encoder/vaapiencoder_base.cpp
> +        rtFormat = VA_RT_FORMAT_YUV420_10BPP;
okay, thanks @xuguangxin .

2016-11-23 06:53 UTC, wudping commented on encoder/vaapiencoder_base.cpp
> +    if (m_videoParamCommon.bitDepth == 10)
okay , thanks @xuguangxin

2016-11-24 05:28 UTC, xuguangxin approved these changes

2016-11-24 05:28 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
> +        rtFormat = getRtFormat(fourcc);
please remove entire switch case and use getRtFormat instead and check the return value

2016-11-24 05:28 UTC, xuguangxin commented on encoder/vaapiencoder_base.cpp
> +    if (m_videoParamCommon.bitDepth > 10 || m_videoParamCommon.bitDepth < 8) {
we do not suport 9 bit too, please use !=

2016-11-24 11:04 UTC, wudping commented on encoder/vaapiencoder_base.cpp
> +    if (m_videoParamCommon.bitDepth > 10 || m_videoParamCommon.bitDepth < 8) {
okay, thanks @xuguangxin

2016-11-24 11:04 UTC, wudping commented on encoder/vaapiencoder_base.cpp
> +        rtFormat = getRtFormat(fourcc);
okay, thanks @xuguangxin

2016-11-24 11:08 UTC, wudping commented
updated, please help to review.

2016-11-25 08:06 UTC, wudping commented
updated again, please help to review, thanks in advance.

2016-11-25 08:37 UTC, xuguangxin commented on encoder/vaapiencoder_hevc.cpp
> +    if ((10 == m_videoParamCommon.bitDepth) && (VAProfileHEVCMain == m_videoParamCommon.profile))
no need check VAProfileHEVCMain

2016-11-28 06:44 UTC, wudping commented on encoder/vaapiencoder_hevc.cpp
> +    if ((10 == m_videoParamCommon.bitDepth) && (VAProfileHEVCMain == m_videoParamCommon.profile))
thanks @xuguangxin .

2016-11-28 06:57 UTC, wudping commented
updated, please help to review. thanks.

2016-11-29 04:03 UTC, xuguangxin commented
merged as b3038909eb2aa1e87738bff412b085f7b537ad40.

2016-11-29 04:03 UTC, closed without merging