265_dec: modify the length of sublayer_hrd_params
01org/libyami pull request #697
Opened 2016-12-30 08:22 UTC by wudping

According to specification 7.4.3.1 and 7.4.3.2.1, the value of
sps_max_sub_layers_minus1 and vps_max_sub_layers_minus1 shall be
in the range of 0 to 6, inclusive, so sublayer_hrd_params[]'s length
should be at least MAXSUBLAYERS(7). Or else, decoding will crash
when decoding some clips.

debug Allegro 8 bit decoding. [VIZ-6406](https://jira01.devtools.intel.com/browse/VIZ-6406?filter=79676)

Signed-off-by: wudping <dongpingx.wu@intel.com>

2016-12-30 08:26 UTC, wudping commented
please help to review.

2017-01-03 02:18 UTC, xuguangxin commented on codecparsers/h265Parser.h
> -        SubLayerHRDParameters sublayer_hrd_params[6];
do we need change fixed_pic_rate_general_flag,  fixed_pic_rate_within_cvs_flag, elemental_duration_in_tc_minus1, low_delay_hrd_flag, cpb_cnt_minus1 seems they use same loop variable maxNumSubLayersMinus1

2017-01-04 05:37 UTC, wudping commented on codecparsers/h265Parser.h
> -        SubLayerHRDParameters sublayer_hrd_params[6];
okay, Thanks @xuguangxin .

2017-01-05 08:52 UTC, wudping commented
updated according to the comments, and set PPS's deblocking filter parameter to SLICE's when the SLICE's deblocking parameter don't present. 
Please help to review.

2017-01-06 04:17 UTC, xuguangxin requested changes

2017-01-06 04:17 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
> +        CHECK_RANGE(slice->beta_offset_div2, -6, 6);
better add CHECK_READ_SE at check this at read location

2017-01-06 04:17 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
>                  slice->num_ref_idx_l1_active_minus1 = pps->num_ref_idx_l1_default_active_minus1;
should we check pps->num_ref_idx_l1_default_active_minus1?

2017-01-06 04:17 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
> +#define CHECK_RANGE(var, min, max)                                               \
could we use this macro for CHECK_READ_BITS and CHECK_READ_UE

2017-01-06 05:05 UTC, wudping commented on codecparsers/h265Parser.cpp
> +        CHECK_RANGE(slice->beta_offset_div2, -6, 6);
okay, Thanks @xuguangxin .

2017-01-06 05:05 UTC, wudping commented on codecparsers/h265Parser.cpp
> +#define CHECK_RANGE(var, min, max)                                               \
okay, Thanks @xuguangxin .

2017-01-11 04:17 UTC, wudping commented
update according to the suggestions, please help to review.

2017-01-16 06:54 UTC, xuguangxin requested changes

2017-01-16 06:54 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
> +#define POWER15 32768
please use (2<<15)

2017-01-16 06:54 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
> +#define POWER32SUB2 4294967294
please use ((2<<32)-2)

2017-01-16 06:54 UTC, xuguangxin commented on codecparsers/h265Parser.cpp
> +            CHECK_READ_UE_LONG(var->var##_max_latency_increase_plus1[i], 0, POWER32SUB2);                        \
why we need CHECK_READ_UE_LONG, POWER32SUB2 is not long, right?

2017-01-17 02:00 UTC, wudping commented
updated according suggestion, please help to review. thanks again.

2017-01-17 03:12 UTC, wudping commented
updated according to suggestions, please help to review..

2017-01-17 04:54 UTC, xuguangxin approved these changes

2017-01-17 04:54 UTC, xuguangxin commented
merged as 125f35d8412252aa67efcb7f13737746a1299f1e

2017-01-17 04:54 UTC, closed without merging