264_enc: modify max_frame_num
01org/libyami pull request #700
Opened 2017-01-13 06:43 UTC by wudping

According to spec, log2_max_frame_num_minus4 should be in
the range[0, 12], so log2_max_frame_num should be in the
range[4, 16].

So as H265.

To fix issue [#679](https://github.com/01org/libyami/issues/679)
Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-01-13 06:43 UTC, wudping commented
to fix issue #679 , please help review.

2017-01-16 03:25 UTC, xuguangxin requested changes
this not fix the problem just delay it from 2^10 to 2^16

2017-01-16 05:49 UTC, wudping commented
Thanks @xuguangxin , I am going to find out the original cause.

2017-02-21 08:02 UTC, xuguangxin commented
close this since it did fix the problem, need new patch to fix this

2017-02-21 08:02 UTC, closed without merging