265dec: modify the scaling list
01org/libyami pull request #701
Opened 2017-01-19 01:08 UTC by wudping

Modifying the functions to derive scaling_list, follow spec.

to fix [VIZ-6406](https://jira01.devtools.intel.com/browse/VIZ-6406)

Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-01-19 01:14 UTC, wudping commented
this patch fixes the HEVC allegro 8 bits decoding failed problem. please help to review. Thanks in advance.

2017-01-19 01:31 UTC, wudping commented
please help to review.

2017-01-20 05:03 UTC, xuguangxin requested changes

2017-01-20 05:03 UTC, xuguangxin commented on codecparsers/h265Parser.h
> +        uint8_t scalingList32x32[6][64];
Please give some comment on this two fields, why we only use 0, 3

2017-01-20 05:03 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +        iqMatrix->ScalingListDC32x32[i] = scalingList->scalingListDC32x32[i * 3];
this need comments too, why you only need i *3

2017-01-20 05:03 UTC, xuguangxin commented on decoder/vaapidecoder_h265.cpp
> +            iqMatrix->ScalingList32x32[i][UpperRightDiagonal32x32[j]] = scalingList->scalingList32x32[i * 3][j];
this need comments too, why you only need i *3

2017-02-06 07:44 UTC, wudping commented on codecparsers/h265Parser.h
> +        uint8_t scalingList32x32[6][64];
okay, thanks @xuguangxin ;

2017-02-06 07:45 UTC, wudping commented on decoder/vaapidecoder_h265.cpp
> +            iqMatrix->ScalingList32x32[i][UpperRightDiagonal32x32[j]] = scalingList->scalingList32x32[i * 3][j];
okay, Thanks @xuguangxin , It's helpful for code reading.

2017-02-06 07:45 UTC, wudping commented on decoder/vaapidecoder_h265.cpp
> +        iqMatrix->ScalingListDC32x32[i] = scalingList->scalingListDC32x32[i * 3];
thanks @xuguangxin  for your careful review.

2017-02-07 00:48 UTC, wudping commented
updated as comments, please help to review. thanks.

2017-02-07 02:25 UTC, xuguangxin approved these changes

2017-02-07 02:28 UTC, merged