265parser: cancel some special value checking
01org/libyami pull request #705
Opened 2017-02-10 08:21 UTC by wudping

As the specification, the value of delta_poc_s0_minus1 should
be in [0, 2^15], but some clip is with -3, so we have to cancel
this value checking to decode it completely.

to fix the decoding error of the one h265 container clip.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-02-10 08:22 UTC, wudping commented
please help to review.

2017-02-13 06:39 UTC, xuguangxin requested changes
If delta_poc_s0_minus1 have problem, delta_poc_s1_minus1 will same problem.

2017-02-13 09:28 UTC, wudping commented
updated according to comment, please help to review,
Thanks @xuguangxin  for your suggestion.

2017-02-14 06:00 UTC, xuguangxin approved these changes

2017-02-14 06:00 UTC, merged