Modify m_maxTbsize to 32 for hevc encoding
01org/libyami pull request #718
Opened 2017-03-07 05:37 UTC by pengche1

Keep it as the same as CU max size.

Signed-off-by: peng.chen <peng.c.chen@intel.com>

2017-03-07 05:39 UTC, xuguangxin commented
@pengche1 , could you give more descriptive log in the commit message?thanks

2017-03-07 05:53 UTC, pengche1 commented
@xuguangxin, do you think below description is enough or not?

 Modify m_maxTbsize to 32 for hevc encoding

    Keep it as the same as CU max size. It makes it possible
    to select bigger TU size for some CUs and improves the
    enoding quality

2017-03-07 07:07 UTC, lizhong1008 commented
@pengche1 , yeah, please change the commit message to  "Keep it as the same as CU max size. It makes it possible to select bigger TU size for some CUs and improves the
encoding quality"

2017-03-08 03:04 UTC, xuguangxin commented
greate @pengche1 , thanks

2017-03-08 03:05 UTC, xuguangxin requested changes
Please change the commit log.thanks

2017-03-08 03:13 UTC, pengche1 commented
Done

2017-03-09 03:15 UTC, xuguangxin approved these changes

2017-03-09 03:15 UTC, merged