travis_CI: add Travis CI to compile every commit
01org/libyami pull request #721
Opened 2017-03-16 07:37 UTC by wudping

move README to README.md, and add the coverity message into
it.

to implement [VIZ-9125](https://jira01.devtools.intel.com/browse/VIZ-9125) based Yizhou's patches.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-03-16 07:59 UTC, xuguangxin requested changes
please help change      https://github.com/01org/libyami-utils line too.

2017-03-16 07:59 UTC, xuguangxin commented on README.md
> +
seems this is little illformatted. https://github.com/wudping/libyami/tree/TravicCI

2017-03-16 09:07 UTC, wudping commented
okay @xuguangxin .

2017-03-17 00:47 UTC, xuguangxin commented
It's ok for this pull request. 
But seems we only build h264 encoder and some of decoders
See https://travis-ci.org/01org/libyami
Could you add more? Please also add v4l2 decoder and encoder

2017-03-17 00:50 UTC, wudping commented
okay, @xuguangxin , Thanks.

2017-03-17 02:44 UTC, xuguangxin approved these changes

2017-03-17 02:44 UTC, merged