Jpeg unit
01org/libyami pull request #725
Opened 2017-03-24 05:54 UTC by wudping

implement JPEG decoderAPI unittest.

to figure out [VIZ-9126](https://jira01.devtools.intel.com/browse/VIZ-9126)

2017-03-24 05:55 UTC, wudping commented
please help to review, thanks.

2017-03-27 04:25 UTC, xuguangxin commented
Hi @uartie , please help to review.
thanks

2017-05-17 00:15 UTC, uartie requested changes

2017-05-17 00:15 UTC, uartie commented on decoder/vaapiDecoderJPEG.h
> +    YamiStatus ensureContext();
this should be a private method

2017-05-17 00:15 UTC, uartie commented on decoder/vaapiDecoderJPEG_unittest.cpp
> -
We should keep this check for the second image buffer decode.  The only difference now is that we don't expect to get a format change on the next decode call.  That is, notice we are testing the decode for different image in the mjpeg sequence `buffer.data = const_cast<uint8_t*>(mjpeg.data() + paramSize);`

2017-05-17 00:48 UTC, uartie commented
The main difference I see in this change is that now we are parsing the jpeg header twice for the first frame.    Probably won't notice any perf impact though.

2017-05-17 00:51 UTC, uartie commented
previous comment edited

2017-05-17 01:00 UTC, uartie commented
ok, maybe just the first image header is parsed twice

2017-05-17 07:40 UTC, wudping reviewed
Agree with you @uartie, just the first image header is parse twice.
We don't need to call VaapiDecoderJPEG::decode() twice for every JPEG frame.

2017-05-17 07:40 UTC, wudping commented on decoder/vaapiDecoderJPEG_unittest.cpp
> -
start() registered for M_SOF0 is empty now, and no YAMI_DECODE_FORMAT_CHANGE signal is triggered excepted for the current resolution is really different from the previous.

2017-05-17 07:40 UTC, wudping commented on decoder/vaapiDecoderJPEG_unittest.cpp
> -
These two frames are the same.

2017-05-17 08:44 UTC, wudping commented
Updated according comment, please help to review. Thanks a lot.

2017-05-17 14:08 UTC, uartie requested changes

2017-05-17 14:08 UTC, uartie commented on decoder/vaapiDecoderJPEG_unittest.cpp
> -
They have the same bit values, but the two frames are different data pointers.  Notice one buffer starts at "mjpeg.data()" offset and the other at "mjpeg.data() + paramSize" offset.  This verifies that the single decoder instance properly handles/decodes multiple images.  This simulates what the api user would do.

2017-05-17 14:14 UTC, uartie commented on decoder/vaapiDecoderJPEG_unittest.cpp
> -
That is, please decode the second image in this test and verify the expectations.

2017-05-18 01:21 UTC, wudping commented
Thanks @uartie , the second JPEG frame in the same buffer decoding is restored to the previous.
Please help to review. Thanks again.

2017-05-18 01:24 UTC, wudping commented
Any misunderstanding I make, please let me know, I will modify it. Thanks.

2017-05-18 01:27 UTC, uartie approved these changes

2017-05-19 07:31 UTC, merged

2017-05-19 07:32 UTC, xuguangxin commented
thanks U.Arite