vp8dec: enable svc-t decoding
01org/libyami pull request #737
Opened 2017-04-27 11:26 UTC by wudping

Support three layers vp8 svc-t decoding.

Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-04-27 11:33 UTC, wudping commented
please help to review, thanks.

2017-05-05 02:17 UTC, xuguangxin requested changes

2017-05-05 02:17 UTC, xuguangxin commented on decoder/vaapidecoder_base.h
> +    virtual bool isSVCTFrame() { return true; }
Why do we need add this to the base?

2017-05-05 02:17 UTC, xuguangxin commented on decoder/vaapidecoder_vp8.cpp
> +    case 0:
Please comments about 0, why we need return true for 0 layer

2017-05-05 02:17 UTC, xuguangxin commented on decoder/vaapidecoder_vp8.cpp
> +    default:
Please return true for default, if you have 3 layers, user want 4 layers, you need decode all 3 for them

2017-05-05 02:17 UTC, xuguangxin commented on interface/VideoDecoderDefs.h
> +    //xxxLayer - layer number, 0: decode all layers, >0: decode up to target layer.
Please remove unsupport things. vp8 not support it, not mean all codecs not support it.

2017-05-05 02:17 UTC, xuguangxin commented on interface/VideoDecoderDefs.h
> +    //xxxLayer - layer number, 0: decode all layers, >0: decode up to target layer.
decode up to the target layer.-> How many layers you want to decode.

2017-05-05 02:21 UTC, wudping commented on decoder/vaapidecoder_base.h
> +    virtual bool isSVCTFrame() { return true; }
Because other codecs may support SVC-T.

2017-05-05 03:14 UTC, wudping commented
updated, thanks.

2017-05-05 03:15 UTC, xuguangxin commented on decoder/vaapidecoder_base.h
> +    virtual bool isSVCTFrame() { return true; }
Different decoder may handle SVC in different way, this not needed in base class

2017-05-05 03:16 UTC, xuguangxin commented on decoder/vaapidecoder_vp8.cpp
> +bool VaapiDecoderVP8::isSVCTFrame()
you can change this to targetFrame

2017-05-05 03:24 UTC, wudping commented
updated, thanks @xuguangxin .

2017-05-09 03:02 UTC, xuguangxin requested changes

2017-05-09 03:02 UTC, xuguangxin commented on decoder/vaapidecoder_base.h
> +    virtual bool targetTemporalFrame() { return true; }
Do not put this in base, it's codec specific feature

2017-05-09 05:29 UTC, wudping commented
Updated, thanks @xuguangxin .

2017-05-11 08:10 UTC, xuguangxin approved these changes

2017-05-12 04:02 UTC, xuguangxin approved these changes

2017-05-12 04:02 UTC, merged