dec_unittest: fix vp9 decode unittest failure on BSW/SKL
01org/libyami pull request #754
Opened 2017-06-28 05:56 UTC by wudping

BSW/SKL do not support VP9 decoding, so vp9 decoding leads to core-dump
in decode unittest.
This patch will skip the unittest when detect that the platform dosen't
support VP9.

to fix issue [741](https://github.com/01org/libyami/issues/741)

Signed-off-by: wudping <dongpingx.wu@intel.com>

2017-06-28 05:56 UTC, wudping commented
please help to review.

2017-06-29 03:17 UTC, xuguangxin requested changes
Please split core changes and unit test changes

2017-06-29 03:17 UTC, xuguangxin commented on decoder/DecoderApi_unittest.cpp
> +        if (YAMI_UNSUPPORTED == status) {
duplicate code here. 
please use
bool checkStatus(YamiStatus status)
to  remove all duplicates

2017-06-29 03:17 UTC, xuguangxin commented on decoder/DecoderApi_unittest.cpp
> +                      << " We can't test this in terminal, the stream is unsupported." << std::endl;
change this to "hw do not support this decoder"

2017-06-29 03:17 UTC, xuguangxin commented on decoder/DecoderApi_unittest.cpp
> +            if (YAMI_UNSUPPORTED == status) {
no call decode call need this, we just need check it in first decode call

2017-06-30 08:34 UTC, wudping commented on decoder/DecoderApi_unittest.cpp
> +            if (YAMI_UNSUPPORTED == status) {
hi @xuguangxin ,
This is necessary actually. Because Yami will return YAMI_DECODE_FORMAT_CHANGE when decoding the first frame.

2017-06-30 13:06 UTC, xuguangxin approved these changes

2017-06-30 13:06 UTC, merged