decoder: enable low latency mode for AVC decoder
01org/libyami pull request #775
Opened 2017-07-26 08:43 UTC by YuJiankang

Signed-off-by: jkyu <jiankang.yu@intel.com>

2017-07-26 10:17 UTC, xuguangxin requested changes

2017-07-26 10:17 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +            it = find_if(m_pictures.begin(), m_pictures.end(), isOutputNeeded);
Could we add isLowLatencyOuptutFrame and combine
isOutputNeeded , and isFrame(*it) && (!m_isOutputStarted || ((*it)->m_poc -m_lastOutputPoc == 1) to the function.

2017-07-26 10:17 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    , m_isOutputStarted(false)
do we need reset this in flush?

2017-07-26 10:22 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +                if (!m_isOutputStarted)
do not need this if and it slow than "m_isOutputStarted = true;" only

2017-07-27 06:32 UTC, YuJiankang commented
updated

2017-08-01 19:25 UTC, uartie commented
please rebase

2017-08-02 07:19 UTC, xuguangxin requested changes

2017-08-02 07:19 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    , m_isOutputStarted(false)
@YuJiankang , any update on this.
could you work with dongping to add some test case for low latency  mode

2017-08-02 07:19 UTC, xuguangxin commented on decoder/vaapidecoder_h264.cpp
> +    m_isOutputStarted = false;
do we need update m_lastOutputPoc here?

2017-08-09 07:20 UTC, xuguangxin approved these changes

2017-08-09 07:20 UTC, merged