Fixes #766: add explicit braces to avoid 'ambiguous else' warning.
01org/libyami pull request #777
Opened 2017-07-27 22:35 UTC by stripes416

Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>

2017-07-27 22:39 UTC, uartie requested changes
Please move the "Fixes ..." blurb to the body of the commit message. Also, a simpler commit message title would be something like "test: fix GCC 7.x warnings/errors" and then move current title into body of message to provide further explanation of what/why.

2017-07-27 23:24 UTC, uartie commented
Also, I'm sure you meant that it Fixes #776 not #766

2017-07-28 00:33 UTC, uartie approved these changes

2017-07-28 00:35 UTC, merged

2017-07-28 00:36 UTC, xuguangxin commented
thanks @stripes416 and @uartie