add gcc compilation option for SDL325
01org/libyami pull request #858
Opened 2018-06-11 09:46 UTC by wangzj0601

2018-06-11 16:36 UTC, uartie requested changes
Invoking gcc before `AC_PROC_CC` check is bad.  Also, compiler might not be gcc.

Even worse, this does not work on all distros/autoconf versions.  Something like `AX_CHECK_COMPILE_FLAG` would be better (https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html).  Unfortunately, this `AX_CHECK_COMPILE_FLAG` m4 macro is not built-in and would require us to track it under project `m4` directory or force users to install autoconf-archive distro package.  I believe the license "exception" for that macro would allow us to track it in this project, but you would need to verify that first.  Or maybe you could find a built-in macro (try googling)?  Perhaps some form of `AC_COMPILE_IFELSE` usage would work.

2018-06-12 04:58 UTC, wangzj0601 commented
I wrote these options into a variable and override it into libyami compilation

2018-06-12 15:53 UTC, uartie requested changes
Please read and understand https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html

Also, why can't you just set custom user flags in your own environment instead?  See configure --help influential environment variables.

2018-06-12 15:53 UTC, uartie commented on Makefile.am
> +	$(LDFLAGS) \
User LDFLAGS, CFLAGS, CXXFLAGS, CPPFLAGS etc. are automatically included already.

2018-06-12 15:53 UTC, uartie commented on autogen.sh
> +
NEVER override user flags in toolchain files.

2018-06-12 15:57 UTC, uartie commented
Rejecting... user flags should be defined by user only.  User flags can negate AM_CFLAGS/CXXFLAGS that are in configure.ac (e.g. `CFLAGS=-Wno-error CXXFLAGS=-Wno-error ./autogen.sh` to turn off AM_ setting of `-Werror`).

2018-06-12 15:57 UTC, closed without merging